name: Update Football Transfers

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:
permissions:
  contents: write
jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Get repository
        uses: actions/checkout@v4

      - name: Get transfers from API-Sports
        env:
          API_KEY: ${{ secrets.API_SPORTS_KEY }}
        run: |
          curl --request GET \
            --url "https://v3.football.api-sports.io/transfers?team=529" \
            --header "x-apisports-key: $API_KEY" \
            --output transfers.json

      - name: Save changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add transfers.json
          git diff --cached --quiet || git commit -m "Update football transfers"
          git push
